marvelcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('comics/', views.comics_index, name='index'),
    path('comics/<int:comic_id>/', views.comics_detail, name='detail'),
    path('comics/create/', views.ComicCreate.as_view(), name='comics_create'),
    path('comics/<int:pk>/update/', views.ComicUpdate.as_view(), name='comics_update'),
    path('comics/<int:pk>/delete/', views.ComicDelete.as_view(), name='comics_delete'),
    path('comics/<int:comic_id>/add_vote/', views.add_vote, name='add_vote'),
    path('comics/<int:comic_id>/add_comic_photo/', views.add_comic_photo, name='add_comic_photo'),
    path('comics/<int:comic_id>/assoc_character/<int:character_id>/', views.assoc_character, name='assoc_character'),
    path('comics/<int:comic_id>/unassoc_character/<int:character_id>/', views.unassoc_character, name='unassoc_character'),
    path('characters/', views.CharacterList.as_view(), name='characters_index'),
    path('characters/<int:pk>/', views.CharacterDetail.as_view(), name='characters_detail'),
    path('characters/create/', views.CharacterCreate.as_view(), name='characters_create'),
    path('characters/<int:pk>/update/', views.CharacterUpdate.as_view(), name='characters_update'),
    path('characters/<int:pk>/delete/', views.CharacterDelete.as_view(), name='characters_delete'),
    path('characters/<int:character_id>/add_character_photo/', views.add_character_photo, name='add_character_photo'),
]

marvelcollector/marvelcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

marvelcollector/main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

RATINGS = (
    ('1', 'Poor'),
    ('2', 'Alright'),
    ('3', 'Good'),
    ('4', 'Very Good'),
    ('5', 'Amazing'),
)


class Character(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, max_length=250)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('characters_detail', kwargs={'pk': self.id})
    

class Comic(models.Model):
    name = models.CharField(max_length=100)
    published = models.DateField()
    writer = models.CharField(max_length=100)
    penciler = models.CharField(max_length=100)
    cover = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    characters = models.ManyToManyField(Character)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'comic_id': self.id })
    
    
class Vote(models.Model):
    date = models.DateField()
    rating = models.CharField(max_length=1, choices=RATINGS, default=RATINGS[0][0])
    comment = models.TextField(default='', max_length=200)
    comic = models.ForeignKey(Comic, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_rating_display()} on {self.date}"
    class Meta:
        ordering = ['-date']

class ComicPhoto(models.Model):
    url = models.CharField(max_length=200)
    comic = models.ForeignKey(Comic, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for comic_id: {self.comic} @{self.url}"
    

class CharacterPhoto(models.Model):
    url = models.CharField(max_length=200)
    character = models.ForeignKey(Character, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for character_id: {self.character} @{self.url}"

marvelcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Vote

class VoteForm(ModelForm):
  class Meta:
    model = Vote
    fields = ['date', 'rating', 'comment']

marvelcollector/main_app/views.py
import uuid
import boto3
import os
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Comic, Character, ComicPhoto, CharacterPhoto
from .forms import VoteForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def comics_index(request):
    comics = Comic.objects.all()
    return render(request, 'comics/index.html', {'comics': comics})

def comics_detail(request, comic_id):
    comic = Comic.objects.get(id=comic_id)
    id_list = comic.characters.all().values_list('id')
    characters_comic_doesnt_have = Character.objects.exclude(id__in=id_list)

    vote_form = VoteForm()
    return render(request, 'comics/detail.html', {'comic': comic, 'vote_form': vote_form, 'characters': characters_comic_doesnt_have})

def add_vote(request, comic_id):
    form = VoteForm(request.POST)
    if form.is_valid():
        new_vote = form.save(commit=False)
        new_vote.comic_id = comic_id
        new_vote.save()
    return redirect('detail', comic_id=comic_id)

class ComicCreate(CreateView):
    model = Comic
    fields = ['name', 'published', 'writer', 'penciler', 'cover', 'description']

class ComicUpdate(UpdateView):
    model = Comic
    fields = '__all__'

class ComicDelete(DeleteView):
    model = Comic
    success_url = '/comics'

class CharacterList(ListView):
  model = Character

class CharacterDetail(DetailView):
  model = Character

class CharacterCreate(CreateView):
  model = Character
  fields = '__all__'

class CharacterUpdate(UpdateView):
  model = Character
  fields = ['name', 'description']

class CharacterDelete(DeleteView):
  model = Character
  success_url = '/characters'

def assoc_character(request, comic_id, character_id):
   Comic.objects.get(id=comic_id).characters.add(character_id)
   return redirect('detail', comic_id=comic_id)

def unassoc_character(request, comic_id, character_id):
   Comic.objects.get(id=comic_id).characters.remove(character_id)
   return redirect('detail', comic_id=comic_id)

def add_comic_photo(request, comic_id):
    # photo-file will be the "name" attribute on the <input type="file">
    comic_photo_file = request.FILES.get('comic_photo-file', None)
    if comic_photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + comic_photo_file.name[comic_photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(comic_photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            ComicPhoto.objects.create(url=url, comic_id=comic_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', comic_id=comic_id)

def add_character_photo(request, character_id):
    # photo-file will be the "name" attribute on the <input type="file">
    character_photo_file = request.FILES.get('character_photo_file', None)
    if character_photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + character_photo_file.name[character_photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(character_photo_file, bucket, key)
            # build the full url string
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            CharacterPhoto.objects.create(url=url, character_id=character_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('characters_detail', pk=character_id)

marvelcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Marvel Collector</h1>
<hr>
<p>Fun Application where you can find stored all the collected Marvel Comics over the years!</p>
 
{% endblock %}

marvelcollector/main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Marvel Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <a href="#" class="brand-logo right">Marvel Collector</a>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'index' %}">All Marvel Comics</a></li>
            <li><a href="{% url 'comics_create' %}">Add a Comic</a></li>
            <li><a href="{% url 'characters_index' %}">All Marvel Characters</a></li>
            <li><a href="{% url 'characters_create' %}">Add a Character</a></li>
          </ul>          
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2023 Marvel Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

marvelcollector/main_app/templates/comics/detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Comic Details</h1>
<a class="waves-effect waves-light btn-small red lighten-1" href="/comics">Go Back</a><br><br>
<div class="row">
  <div class="col s12">
    <div class="col s6">
      <div class="card-medium">
        <div class="card-image">
          {% for comic_photo in comic.comicphoto_set.all %}
          <img src="{{ comic_photo.url }}" alt="comic cover photo">
          {% empty %}
          <div class="card-panel orange-text center-align">No Photo Uploaded</div>
          {% endfor %}
        </div>
        <div class="card-content">
          <h4 class="card-title">{{ comic.name }}</h4>
          <h5>Published: {{ comic.published }}</h5>
          <h6>Writer: {{ comic.writer }}</h6>
          <h6>Cover: {{ comic.cover }}</h6>
          <p>{{ comic.description }}</p>
        </div>
        <div class="card-action">
          <a class="waves-effect waves-light btn-small red lighten-1" href="{% url 'comics_update' comic.id %}">Edit</a>
          <a class="waves-effect waves-light btn-small red lighten-1"
            href="{% url 'comics_delete' comic.id %}">Delete</a>
        </div>
        <form action="{% url 'add_comic_photo' comic.id %}" enctype="multipart/form-data" method="POST"
          class="card-panel">
          {% csrf_token %}
          <input type="file" name="comic_photo-file">
          <br><br>
          <button type="submit" class="btn-small red lighten-1">Upload Cover Photo</button>
        </form>
      </div>
    </div>
    <div class="col s6">
      <h4>Vote here!</h4>
      <form action="{% url 'add_vote' comic.id %}" method="POST">
        {% csrf_token %}
        {{ vote_form.as_p }}
        <input type="submit" class="btn red lighten-1" value="Add Vote">
      </form>
      <table class="striped">
        <thead>
          <tr>
            <th>Voted on</th>
            <th>Comment</th>
            <th>Rated</th>
          </tr>
        <tbody>
          {% for vote in comic.vote_set.all %}
          <tr>
            <td>{{ vote.date }}</td>
            <td>{{ vote.comment }}</td>
            <td>{{ vote.get_rating_display }}</td>
          </tr>
          {% endfor %}
        </tbody>
        </thead>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col s6">
      <h3>Marvel's Characters</h3>
      {% if comic.characters.count %}
      {% for character in comic.characters.all %}
      <div class="card">
        <div class="card-content">
          <h4 class="card-title">
            {{ character.name }}
          </h4>
        </div>
        <div class="card-action">
          <form action="{% url 'unassoc_character' comic.id character.id %}" method="POST">
            {% csrf_token %}
            <button class="waves-effect waves-light btn-small red lighten-1" type="submit" class="btn">Remove</button>
          </form>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <h5>No Characters Yet</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Characters</h3>
      {% if characters.count %}
      {% for character in characters.all %}
      <div class="card">
        <div class="card-content">
          <h4 class="card-title">
            {{ character.name }}
          </h4>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_character' comic.id character.id %}" method="POST">
            {% csrf_token %}
            <button class="waves-effect waves-light btn-small red lighten-1" type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <h5> You inserted in {{comic.name}} all the Marvel's characters that were available!</h5>
      {% endif %}
    </div>
  </div>

  <script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
    });
    const selectEl = document.getElementById('id_rating');
    M.FormSelect.init(selectEl);
  </script>
  {% endblock %}

marvelcollector/main_app/templates/comics/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>All Comics</h1>
{% for comic in comics %}
<div class="row">
    <div class="col s12 m7">
      <div class="card">
        <div class="card-content">
          <h5>{{ comic.name }}</h5>
          <h6>Published: {{ comic.published }}</h6>
        </div>
        <div class="card-action">
          <a href="{% url 'detail' comic.id %}">Comic's Details</a>
        </div>
      </div>
    </div>
</div>
{% endfor %}


{% endblock %}

marvelcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>HomePage</h1>

{% endblock %}

marvelcollector/main_app/templates/main_app/character_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Character</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'characters_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

marvelcollector/main_app/templates/main_app/character_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Character Details</h1>
<a class="waves-effect waves-light btn-small red lighten-1" href="/characters">Go Back</a><br><br>
<div class="row">
    <div class="col s12 m7">
        <div class="card-medium">
            <div class="card-image">
                {% for character_photo in character.characterphoto_set.all %}
                <img src="{{ character_photo.url }}" alt="character photo">
                {% empty %}
                <div class="card-panel orange-text center-align">No Photo Uploaded</div>
                {% endfor %}
            </div>
            <div class="card-content">
                <h4 class="card-title">{{ character.name }}</h4>
                <p>{{ character.description }}</p>
            </div>
            <div class="card-action">
                <a class="waves-effect waves-light btn-small red lighten-1" href="{% url 'characters_update' character.id %}">Edit</a>
                <a class="waves-effect waves-light btn-small red lighten-1"
                    href="{% url 'characters_delete' character.id %}">Delete</a>
            </div>
            <form action="{% url 'add_character_photo' character.id %}" enctype="multipart/form-data" method="POST"
                class="card-panel">
                {% csrf_token %}
                <input type="file" name="character_photo_file">
                <br><br>
                <button type="submit" class="btn-small red lighten-1">Upload Character Photo</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

marvelcollector/main_app/templates/main_app/character_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Character</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn red lighten-1">
  </form>
{% endblock %}

marvelcollector/main_app/templates/main_app/character_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Characters' List</h1>

{% for character in character_list %}
  <a href="{% url 'characters_detail' character.id %}">
    <div class="card">
        <div class="card-content">
            <h4 class="orange-text">{{ character.name }}</h4>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

marvelcollector/main_app/templates/main_app/comic_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Comic</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn red lighten-1">
    <a class="waves-effect waves-light btn-small red lighten-1" href="{% url 'detail' comic.id %}">Cancel</a>
  </form>
{% endblock %}

marvelcollector/main_app/templates/main_app/comic_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
  <h1>Add Comic</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn red lighten-1">
  </form>
{% endblock %}